include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas
    - prefer_single_quotes
    - sort_constructors_first
    - prefer_expression_function_bodies
    - prefer_int_literals
    - unnecessary_lambdas
    - always_put_required_named_parameters_first
    - prefer_final_in_for_each

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint
  