name: meditation
description: "Meditation App"
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

  go_router: ^14.8.1

  # state management
  riverpod: ^2.0.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.0.2

  # code generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # audio player
  just_audio: ^0.9.46
  rxdart: ^0.28.0
  audio_session: ^0.1.25
  just_audio_background: ^0.0.1-beta.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # code generation
  freezed: ^2.3.2
  json_serializable: ^6.7.1
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/mp3s/
